name: Terraform GCP Deployment

on:
  push:
    branches:
      - main  # You can specify any branch you want to trigger the pipeline

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Authenticate to Google Cloud
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" > ${HOME}/gcloud-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} 

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0 # Set the Terraform version you need

      - name: Terraform Init
        run: terraform init
        working-directory: ./testing creds

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./testing creds

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./testing creds
        # Note: Consider removing -auto-approve if you want manual approval for apply
