name: Terraform GCP Deployment

on:
  push:
    branches:
      - main  # You can specify any branch you want to trigger the pipeline

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - id: auth
        uses: google-github-actions/auth@v2.0.0  
        with:
          workload_identity_provider: 'projects/604435195200/locations/global/workloadIdentityPools/wifp100/providers/github'
          service_account: 'sheharyar123@manifest-ocean-440312-h9.iam.gserviceaccount.com'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0 # Set the Terraform version you need

      - name: Terraform Init
        run: terraform init
        working-directory: ./testing creds

      - name: Terraform plan
        run: terraform plan
        working-directory: ./testing creds

      - name: Terraform Apply
        run: terraform apply -var-file=variables.tfvars -auto-approve
        working-directory: ./testing creds
        # Note: Consider removing -auto-approve if you want manual approval for apply
